name: Publish a new release from tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          chmod +x ./release.sh
          ./release.sh
      - name: hash
        run: echo ${{ github.sha }} > release.sha
      - name: access secrets
        run: |
          chmod +x ./print-secret.sh
          echo $TS
          ./print-secret.sh
        env:
          TS: ${{ secrets.TEST_SECRET }}
      - name: prepare multiline string
        run: |
          MLS=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MLS="${MLS//'%'/'%25'}"
          MLS="${MLS//$'\n'/'%0A'}"
          MLS="${MLS//$'\r'/'%0D'}"
          echo "::set-output name=content::$MLS"
        id: prepare-multiline
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: This is a release ${{ steps.prepare-multiline.outputs.content }}!
          files: |
            release.txt
            release.sha
