name: Publish a new release from tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          chmod +x ./release.sh
          ./release.sh
      - name: hash
        run: echo ${{ github.sha }} > release.sha
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: This is a release!
          files: |
            release.txt
            release.sha
