name: Publish a new release from tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          chmod +x ./release.sh
          ./release.sh
      - name: hash
        run: echo ${{ github.sha }} > release.sha
      - name: get release version
        run: |
          echo $GITHUB_REF
          echo "R_V=Ver_${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
        id: get-release-version
      - name: access secrets
        run: |
          chmod +x ./print-secret.sh
          echo $TS
          ./print-secret.sh
        env:
          TS: ${{ secrets.TEST_SECRET }}
      - name: prepare multiline string
        run: |
          chmod +x output-ml-string.sh
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "content<<$EOF" >> "$GITHUB_OUTPUT"
          ./output-ml-string.sh >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
        id: prepare-multiline
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: This is a release ${{ steps.get-release-version.outputs.R_V }} ${{ steps.prepare-multiline.outputs.content }}!
          files: |
            release.txt
            release.sha
