name: Publish a new release from tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          chmod +x ./release.sh
          ./release.sh
      - name: hash
        run: echo ${{ github.sha }} > release.sha
      - name: access secrets
        run: |
          chmod +x ./print-secret.sh
          echo $TS
          ./print-secret.sh
        env:
          TS: ${{ secrets.TEST_SECRET }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: This is a release ${TS} !
          files: |
            release.txt
            release.sha
        env:
          TS: ${{ secrets.TEST_SECRET }}